set "SOURCE=%~dp0"
set "SOURCE=%SOURCE:~0,-1%"
set "BUILD=build/emscripten"
if "%TOOLCHAINS%" == "" set "TOOLCHAINS=%SOURCE%\CMake\Toolchains"
cmake -E make_directory "%BUILD%" && cmake -E chdir "%BUILD%" cmake -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE="%TOOLCHAINS%\emscripten.toolchain.cmake" -DCMAKE_BUILD_TYPE=Release "%SOURCE%" && cmake --build "%BUILD%"